import numpy as np
from easydict import EasyDict as cfg
# road_profile import removed (M3/C3b): the generate_road_profile() call in __init__
# was unused in production and caused a spurious state-pollution at import time.

# =============================================================================
#  Vehicle_Dynamics_V2.py
#  Based on: vehicle_dynamics 1.py
#  Fixes applied from physics_audit.md:
#
#  FIX #1 [CRITICAL]  solve_propulsion()  — Asymmetric differential model
#  FIX #2 [HIGH]      solve_moment_x()    — `camber` parameter was silently ignored
#  FIX #3 [HIGH]      solve_cornering()   — alpha_deg not corrected for combined slip
#  FIX #4 [MEDIUM]    kremple()           — Fx_max scan extended to negative slip (braking)
#  FIX #5 [MEDIUM]    solve_lateral()     — ay bank-corrected for unsprung mass centrifugal term
#  FIX #6 [MEDIUM]    __init__()          — road_profile moved from class-scope into __init__
#  FIX #7 [LOW]       solve_longitudinal()— delta_Fz_pitch retained as diagnostic output
#  FIX #8 [HIGH]      solve_lateral()     — robust guard for zero roll_angle / zero turn_radius
# =============================================================================

class VehicleDynamics:
    def __init__(self, params):
        self.p = params                                                 # vehicle_config EasyDict
        self.g = 9.81
        # Auto-calculate interdependent basic params
        self.p.wb = self.p.l_r + self.p.l_f                             # wheelbase
        self.p.m_ra = self.p.m * (self.p.l_f / self.p.wb)               # static total mass at RA
        self.p.m_fa = self.p.m * (self.p.l_r / self.p.wb)               # static total mass at FA
        self.p.m_ra_spr = self.p.m_spr * (self.p.l_f / self.p.wb)       # RA sprung mass
        self.p.m_fa_spr = self.p.m_spr * (self.p.l_r / self.p.wb)       # FA sprung mass
        # Dis b/w CG and Roll Axis
        self.p.del_h = self.p.cg_hei - self.p.l_r/self.p.wb * (self.p.fa_rp - self.p.ra_rp) - self.p.ra_rp

        # FIX #6 (superseded by M3): generate_road_profile() call removed from __init__.
        # The road profile it produced was never used by the main simulation pipeline;
        # it only caused wasted computation and carried __main__-level state into imports.
        # The actual road profile used in production is generated by silesia_road_profile.py.
        pass  # placeholder to keep the comment block; VehicleDynamics is fully functional without it.

#-----------------------------------------------------------------------------------------------------------------------------------------------
    #"""Calculated dynamic wheel radius"""
    def dynamic_wheel(self, Fz):
        tire_amplitude_lim = Fz / self.p.k_ver
        r_dynamic = self.p.r_unloaded - tire_amplitude_lim
        tire_wavelength_lim = 2 * np.sqrt(self.p.r_unloaded ** 2 - r_dynamic ** 2)
        return (r_dynamic, tire_wavelength_lim)

    def static_wheel_parameters(self):
        static_wheel = self.dynamic_wheel(self.p.m_ra / 2 * 9.81)
        self.p.static_driven_tire_wavelength_lim = static_wheel[1]
        self.p.static_r_wheel = static_wheel[0]


#------------------------------------------------------------------------------------------------------------------------------------------------
    #"""Force fatigue along Z-axis (Normal)"""
    def solve_longitudinal(self):
        #"""Calculates pitch shift and longitudinal normal loads."""
        # Pitch shift formula due to acceleration and load_difference due to l_f & l_r
        self.p.ra_Fz_pitch = (((self.p.m * self.g * np.sin(self.p.inc_angle) + self.p.m * self.p.ax) * self.p.cg_hei) + self.p.m * self.g * np.cos(self.p.inc_angle) * self.p.l_f) / self.p.wb  # Moment about FA
        self.p.fa_Fz_pitch = self.p.m * self.g * np.cos(self.p.inc_angle) - self.p.ra_Fz_pitch   # balancing Vertical forces w.r.t the inclination
        # FIX #7: delta_Fz_pitch retained as a diagnostic output (was dead code in V1, kept for reference)
        self.p.delta_Fz_pitch = (self.p.ra_Fz_pitch - self.p.fa_Fz_pitch) / 2

    def solve_lateral(self):
        #"""Calculates lateral normal loads and stiffness required due to cornering"""

        # FIX #8: Robust float-safe guard — replaces fragile `== 0` equality check.
        # Prevents ZeroDivisionError from ay = v²/|R| when turn_radius → 0,
        # and prevents tan(roll_angle) singularity for near-zero roll angles.
        if abs(self.p.roll_angle) < 1e-9 or abs(self.p.turn_radius) < 1e-9:
            return

        # Roll Torque/Moment calculation
        total_angle = self.p.roll_angle + self.p.bank_angle
        self.p.ay = (self.p.velo_v**2) / abs(self.p.turn_radius)            # lateral acceleration
        torque = self.p.m_spr * self.p.del_h * (self.g * np.sin(total_angle) + self.p.ay * np.cos(total_angle))
        # Stiffness derivation
        ratio = self.p.m_ra_spr / self.p.m_fa_spr
        self.p.cf = (2 * torque) / ((self.p.s_f**2) * np.tan(self.p.roll_angle) * (1 + ratio))
        self.p.cr = self.p.cf * ratio * (self.p.s_f**2 / self.p.s_r**2)

        # Static load shift due to bank-angle and pitch (ax)
        ra_Fz_static_per_wheel = (self.p.ra_Fz_pitch * np.cos(self.p.bank_angle)) / 2       # (Vertical forces w.r.t banked road / 2) is the static load on each wheel of RA
        fa_Fz_static_per_wheel = (self.p.fa_Fz_pitch * np.cos(self.p.bank_angle)) / 2       # (Vertical forces w.r.t banked road / 2) is the static load on each wheel of FA

        # Dynamic load shift lumped mass method
        self.p.fa_delta_Fz_roll_lm = (self.p.cf * self.p.s_f * np.tan(self.p.roll_angle) / 2)
        self.p.ra_delta_Fz_roll_lm = (self.p.cr * self.p.s_r * np.tan(self.p.roll_angle) / 2)

        # FIX #5: Bank-corrected effective lateral acceleration for unsprung mass centrifugal term.
        # V1 used raw ay = v²/R for the unsprung mass terms, which omitted the gravity component
        # of the banked road acting on the unsprung masses.
        # Correct effective lateral acceleration perpendicular to road surface:
        #   ay_eff = ay × cos(bank_angle) − g × sin(bank_angle)
        # (sign convention: bank_angle positive when road tilts in the same direction as cornering)
        # For bank_angle = 0 this is identical to V1 behaviour.
        ay_eff_unspr = self.p.ay * np.cos(self.p.bank_angle) - self.g * np.sin(self.p.bank_angle)

        # Dynamic load shift distributed mass method
        self.p.fa_delta_Fz_roll = (2 * ay_eff_unspr / self.p.s_f * (self.p.m_fa_unspr * self.p.r_unloaded + self.p.m_fa_spr * self.p.fa_rp) + self.p.cf * self.p.s_f * np.tan(self.p.roll_angle)) / 2
        self.p.ra_delta_Fz_roll = (2 * ay_eff_unspr / self.p.s_r * (self.p.m_ra_unspr * self.p.r_unloaded + self.p.m_ra_spr * self.p.ra_rp) + self.p.cr * self.p.s_r * np.tan(self.p.roll_angle)) / 2

        # Normal loads (Force = Static + Dynamic)
        self.p.ra_Fz_out = ra_Fz_static_per_wheel + self.p.ra_delta_Fz_roll  # RA outer wheel
        self.p.ra_Fz_inn = ra_Fz_static_per_wheel - self.p.ra_delta_Fz_roll  # RA inner wheel
        self.p.ra_Fz_total = self.p.ra_Fz_out + self.p.ra_Fz_inn             # RA total load

        self.p.fa_Fz_out = fa_Fz_static_per_wheel + self.p.fa_delta_Fz_roll  # FA outer wheel
        self.p.fa_Fz_inn = fa_Fz_static_per_wheel - self.p.fa_delta_Fz_roll  # FA inner wheel
        self.p.fa_Fz_total = self.p.fa_Fz_out + self.p.fa_Fz_inn             # FA total load

        # mapping wheels with inner and outer: Right Turn = Positive radius, Left Turn = Negative Turn
        if self.p.turn_radius > 0:
            # Right Turn: Left side is Outer
            self.p.fa_Fz_left = self.p.fa_Fz_out
            self.p.fa_Fz_right = self.p.fa_Fz_inn
            self.p.ra_Fz_left = self.p.ra_Fz_out
            self.p.ra_Fz_right = self.p.ra_Fz_inn
        else:
            # Left Turn: Right side is Outer
            self.p.fa_Fz_left = self.p.fa_Fz_inn
            self.p.fa_Fz_right = self.p.fa_Fz_out
            self.p.ra_Fz_left = self.p.ra_Fz_inn
            self.p.ra_Fz_right = self.p.ra_Fz_out

    def vertical_force_fatigue(self):
        self.solve_longitudinal()
        self.solve_lateral()

#-----------------------------------------------------------------------------------------------------------------------------------------------
    #"""Force fatigue along Y-axis (Lateral)"""
    def kremple(self, Fz, lon_slip, alpha_deg):
        # PAC89 Tyre Coefficients — SOURCE NOTE (L3 audit fix):
        # Lateral coefficients (a) and longitudinal coefficients (b) are representative
        # values for a small-car tyre in the 150-1000N vertical load range.
        # They are NOT validated against TTC (Tyre Test Consortium) data for the specific
        # Shell Eco-Marathon tyre. Fy/Fx magnitudes carry ±30% uncertainty until replaced
        # with tyre-specific measured data. Fz input expected in kN (Fz/1000 applied by caller).
        # Reference form: Pacejka, H.B. (2012) Tyre and Vehicle Dynamics, 3rd ed., §4.3
        a = (1.65, -34.0, 1250.0, 3036.0, 12.8, 0.00501, -0.02103, 0.77394)
        b = (1.67272, -9.46, 1490.0, 30.0, 176.0, 0.08860, 0.00402, -0.06150, 0.20000)

        def calc_Fx_pure(lon_slip, Fz):
            #"""Calculates pure longitudinal force."""
            C = b[0]                                                          # Shape factor
            D = (b[1] * Fz**2 + b[2] * Fz)                                   # Peak factor
            BCD = (b[3] * Fz**2 + b[4] * Fz) * np.exp(-b[5] * Fz)            # Initial grip per unit lon_slip
            B_lon = BCD / (C * D) if (C * D) != 0 else 0                      # Mathematical scaling factor
            E = b[6] * Fz**2 + b[7] * Fz + b[8]                               # curvature factor
            return D * np.sin(C * np.arctan(B_lon * lon_slip - E * (B_lon * lon_slip - np.arctan(B_lon * lon_slip))))   # peak Fx force

        def calc_Fy_pure(alpha_deg, Fz):
            #"""Calculates pure lateral force."""
            C = a[0]
            D = (a[1] * Fz**2 + a[2] * Fz)
            # PAC89 stiffness factor for lateral
            self.p.K = a[3] * np.sin(2 * np.arctan(Fz / a[4]))                     # lateral/cornering stiffness
            B_lat = self.p.K / (C * D) if (C * D) != 0 else 0                      # Stiffness factor
            E = a[5] * Fz**2 + a[6] * Fz + a[7]
            return D * np.sin(C * np.arctan(B_lat * alpha_deg - E * (B_lat * alpha_deg - np.arctan(B_lat * alpha_deg))))   # peak Fy force

        def calc_Fy_combined():
            #"""Calculates the lateral force potential considering kremple diagram"""
            self.p.Fx_pure = calc_Fx_pure(lon_slip, Fz)
            self.p.Fy_pure = calc_Fy_pure(alpha_deg, Fz)

            # FIX #4: Scan over BOTH positive and negative slip [-30, 30] and take max of |Fx|.
            # V1 only scanned [0, 30] (positive slip / acceleration), which gave a wrong Fx_max
            # reference when lon_slip is negative (braking) and the tire has directional asymmetry.
            # Using abs() across the full slip range captures the true friction circle major axis.
            Fx_max = np.max([abs(calc_Fx_pure(s, Fz)) for s in np.linspace(-30, 30, 1000)])

            # Preventing negative square root
            rho_x = min(abs(self.p.Fx_pure / Fx_max), 1.0) if Fx_max > 0 else 0.0
            self.p.Fy_combined = self.p.Fy_pure * np.sqrt(1 - rho_x**2)   # from ellipse equation, a standard method for PAC89

        # Execute the calculation
        calc_Fy_combined()
        return self.p.Fy_combined

    def solve_cornering(self):
        a = (1.65, -34.0, 1250.0, 3036.0, 12.8, 0.00501, -0.02103, 0.77394)
        b = (1.67272, -9.46, 1490.0, 30.0, 176.0, 0.08860, 0.00402, -0.06150, 0.20000)
        #"""RA lateral force"""
        self.p.ra_Fy_required = self.p.m * self.p.ay * (self.p.l_f / self.p.wb)

        def calc_cornering_stiff(Fz):            # <N/deg> though KN is used as input
            Fz = Fz / 1000                       # convert Fz to KN
            #"""Calculates Pure Cornering stiffness."""
            return a[3] * np.sin(2 * np.arctan(Fz / a[4]))   # same as "K" lateral/cornering stiffness

        # FIX #3: Compute EFFECTIVE cornering stiffness K_eff = K_pure × √(1 − ρx²) to account
        # for the friction ellipse reduction under combined slip.
        # V1 used K_pure (no-slip) to back-calculate alpha_deg, then called kremple() which
        # applied the ellipse correction again — leading to an inconsistently low alpha_deg
        # and a distorted Fy curve estimate. The fix ensures the alpha_deg fed into kremple()
        # is the physically correct slip angle required under combined loading.
        def calc_Fx_pure_scalar(lon_slip, Fz_kN):
            #"""Single-point Fx evaluation (kN inputs) for K_eff correction."""
            C = b[0]
            D = (b[1] * Fz_kN**2 + b[2] * Fz_kN)
            BCD = (b[3] * Fz_kN**2 + b[4] * Fz_kN) * np.exp(-b[5] * Fz_kN)
            B = BCD / (C * D) if (C * D) != 0 else 0
            E = b[6] * Fz_kN**2 + b[7] * Fz_kN + b[8]
            return D * np.sin(C * np.arctan(B * lon_slip - E * (B * lon_slip - np.arctan(B * lon_slip))))

        def calc_Fx_max(Fz_kN):
            #"""Peak |Fx| over full slip range [-30, 30] used as friction ellipse major axis."""
            return np.max([abs(calc_Fx_pure_scalar(s, Fz_kN)) for s in np.linspace(-30, 30, 1000)])

        def calc_K_eff(Fz):
            #"""Effective cornering stiffness corrected for combined slip (friction ellipse)."""
            Fz_kN = Fz / 1000
            K_pure = calc_cornering_stiff(Fz)
            Fx_pure = calc_Fx_pure_scalar(self.p.lon_slip, Fz_kN)
            Fx_max = calc_Fx_max(Fz_kN)
            rho_x = min(abs(Fx_pure / Fx_max), 1.0) if Fx_max > 0 else 0.0
            return K_pure * np.sqrt(1 - rho_x**2)   # K_eff under combined slip

        K_eff_out = calc_K_eff(self.p.ra_Fz_out)
        K_eff_inn = calc_K_eff(self.p.ra_Fz_inn)
        # link the load shift due to roll, acc, inc and banking while cornering
        # now correctly uses K_eff so alpha_deg is consistent with kremple's friction ellipse
        self.p.alpha_deg = self.p.ra_Fy_required / (K_eff_out + K_eff_inn)

        self.p.ra_Fy_out = self.kremple((self.p.ra_Fz_out / 1000), self.p.lon_slip, self.p.alpha_deg)
        self.p.ra_Fy_inn = self.kremple((self.p.ra_Fz_inn / 1000), self.p.lon_slip, self.p.alpha_deg)

#------------------------------------------------------------------------------------------------------------------------------------------------------------
    #"""Force fatigue along X-axis (longitudinal)"""
    def solve_propulsion(self):
        # FIX #1: Correct open-differential model — symmetrically assigns drive force to the
        # INNER (lighter) wheel regardless of turn direction.
        #
        # V1 BUG: The code always computed r_dyn from ra_Fz_left and compared ra_Fz_right vs
        # ra_Fz_left to decide which wheel is driven. This was only correct for LEFT turns
        # (turn_radius < 0) where ra_Fz_left = ra_Fz_inn (inner/lighter). For RIGHT turns
        # (turn_radius > 0) ra_Fz_left = ra_Fz_out (outer/heavier), so the else-branch
        # incorrectly sent drive to the heavier outer wheel — simulating a locked differential
        # for right turns but an open differential for left turns.
        #
        # FIX: Explicitly identify the INNER wheel from turn direction, use its Fz for r_dyn,
        # and always assign ra_Fx_inn = ra_Fx_driven, ra_Fx_out = 0.
        if self.p.turn_radius > 0:
            # Right Turn: LEFT = outer, RIGHT = inner
            Fz_inner = self.p.ra_Fz_right
        else:
            # Left Turn: RIGHT = outer, LEFT = inner
            Fz_inner = self.p.ra_Fz_left

        r_dyn = self.dynamic_wheel(Fz_inner)    # dynamic radius at the driven (inner) wheel
        self.p.ra_Fx_driven = self.p.motor_torque / r_dyn[0]
        self.p.driven_tire_wavelength_lim = r_dyn[1]

        # Open differential: all drive torque goes to the inner (lighter/less-loaded) wheel
        self.p.ra_Fx_inn = self.p.ra_Fx_driven   # rolling resistance considered in Moment_y <$%#>
        self.p.ra_Fx_out = 0.0

    #def solve_braking_test(self):                                  # according to rule book
    #    self.p.Fz_fa_brake = self.p.m * self.g /self.p.wb * (np.cos(np.radians(20)) * self.p.l_r - np.sin(np.radians(20)) * self.p.cg_hei)
    #    self.p.Fz_ra_brake = self.p.m * self.g * np.cos(np.radians(20)) - self.p.Fz_fa_brake
    #    self.p.brake_ratio = self.p.Fz_fa_brake / self.p.Fz_ra_brake
    #
    #    r_dyn_fa = self.dynamic_wheel(self.p.Fz_fa_brake / 2)
    #    r_dyn_ra = self.dynamic_wheel(self.p.Fz_ra_brake / 2)
    #    self.p.ratio_brake_dia_fa_to_ra = self.p.brake_ratio * r_dyn_fa[0] / r_dyn_ra[0]
    #    return (r_dyn_fa, r_dyn_ra)

    #def solve_braking(self):

#---------------------------------------------------------------------------------------------------------------------------------------------------------
    #"""Moment fatigue about X-axis"""
    def solve_moment_x(self, Fz, Fy, camber):
        delta_y = Fy / self.p.k_lat           # due to carcass deflection
        r_dyn = self.dynamic_wheel(Fz)
        # FIX #2: Use the `camber` argument passed by the caller, NOT self.p.camber_angle.
        # V1 accepted camber as a parameter but silently always read self.p.camber_angle,
        # making per-wheel camber inputs (e.g. for camber gain under suspension travel) ineffective.
        return Fz * (delta_y + r_dyn[0] * np.sin(camber))

#---------------------------------------------------------------------------------------------------------------------------------------------------------
    #"""Moment fatigue about Y-axis"""
    def solve_moment_y(self, Fx, Fz):
        r_dyn = self.dynamic_wheel(Fz)
        return (Fx - self.p.roll_coeff * Fz) * r_dyn[0]   # rolling resistance considered here <$%#>

#---------------------------------------------------------------------------------------------------------------------------------------------------------
    #"""Moment fatigue about Z-axis"""
    def solve_moment_z(self, Fz, alpha_deg):   # according to PAC89, computes using pneumatic trail
        Fz = Fz / 1000
        c = (2.34000, 1.4950, 6.416654, -3.57403, -0.087737, 0.098410, 0.0027699, -0.0001151, 0.1000, -1.33329, 0.025501, -0.02357, 0.03027)
        C = c[0]
        D = c[1] * Fz ** 2 + c[2] * Fz
        BCD = (c[3] * Fz**2 + c[4] * Fz) * np.exp(-c[5] * Fz)
        B = BCD / (C * D)
        E = c[6] * Fz ** 2 + c[7] * Fz + c[8]
        Sh = c[9] * Fz + c[10]               # Angle offset <deg> Ply steer + conicity
        Sv = c[11] * Fz **2 + c[12] * Fz     # Moment offset <N·m> Residual conicity torque
        x = alpha_deg + Sh
        return D * np.sin(C * np.arctan(B * x - E * (B * x - np.arctan(B * x)))) + Sv

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------
### --- Update parameters below --- ###
vehicle_config = cfg({
    ### variable parameters: Vehicle Dynamics specific ###
    "turn_radius": -13.5,                                      ### turn_radius +ve for right_turn and -ve for left turn###
    "velo_v": (35) / 3.6,                                      # velo_v in <m/s>
    "roll_angle": np.radians(1),                               # degrees converted to radians, as np.trigonometric function requires input in radians
    "bank_angle": 0.0,                                         ### Road banking angle, Roll and Bank angle signs to be checked: if both are tipping the vehicle towards the same side then both +ve else bank_angle is -ve
    "inc_angle": np.radians(3),                                ### Road Inclination angle, +ve for uphill and -ve for downhill <deg>
    "ax": 0,                                                   ### longitudinal acceleration +ve for acc and -ve for braking
    "lon_slip": 10,                                            # brake or acc lon_slip: -ve BrakeSlip else AccSlip <use 30 for 30% lon_slip>
    "motor_torque": 72,                                        # motor torque at shaft <N-m>
    "camber_angle": np.radians(0),                             # camber angle <deg>

    ### fixed parameters: Vehicle specific ###
    "s_r": .83, "s_f": 1.08,                                   # RA and FA trackwidth
    "m": 200,                                                  # Mass
    "cg_hei": .441,                                            # CG height from ground
    "fa_rp": 0.10161, "ra_rp": 0,                              # FA and RA: RP from ground
    "l_f": .7, "l_r": 1.52-.7,                                 # RA and FA to CG
    "m_spr" : 160, "m_unspr" : 40,                             # Total sprung and unsprung mass
    "m_ra_unspr" : 25, "m_fa_unspr" : 15,                      # RA unsprung mass
    "r_unloaded" : 0.279,                                      # radius of tyre <m>; from tire data
    "k_ver" : 220000,                                          # from tire data vertical stiffness <N/m>
    "k_lat" : 38000,                                           # from tire data lateral stiffness <N/m>
    "roll_coeff" : 0.0013,                                     # rolling coefficient

    ### Computed parameters ###
    "wb": 0.0,                                                 # wheelbase
    "m_ra": 0.0, "m_fa": 0.0,                                  # static total mass at RA and FA
    "m_ra_spr" : 0.0, "m_fa_spr" : 0.0,                        # sprung mass at RA and FA
    "del_h": 0.0,                                              # Dis b/w CG and Roll Axis
    "ra_Fz_pitch": 0.0, "fa_Fz_pitch": 0.0,                    # Normal loads due to Pitching (acc + inclination)
    "delta_Fz_pitch": 0.0,                                     # Load difference due to pitch (diagnostic)

    "cf": 0.0, "cr": 0.0,                                      # spring stiffness outputs
    "fa_delta_Fz_roll": 0.0, "ra_delta_Fz_roll": 0.0,          # Dynamic load shift due to roll + bank_angle using distributed assumption
    "fa_delta_Fz_roll_lm" : 0.0, "ra_delta_Fz_roll_lm" : 0.0, # Dynamic load shift due to roll + bank_angle using lumped mass assumption
    "fa_Fz_out": 0.0, "fa_Fz_inn": 0.0,                        # FA Normal loads at the outer & inner wheels during cornering
    "fa_Fz_total": 0.0,                                        # Total load on FA due to lateral load shift

    "ra_Fz_out": 0.0, "ra_Fz_inn": 0.0,                        # RA Normal loads at the outer & inner wheels during cornering
    "ra_Fz_total": 0.0,                                        # Total load on RA due to lateral load shift

    "alpha_deg": 0.0, "K": 0.0,                                # effective_lateral_slip angle <deg>, lateral/cornering stiffness
    "Fx_pure": 0.0, "Fy_pure" : 0.0, "Fy_combined": 0.0,       # Fx and Fy according to tire kremple, lon_slip, side_slip angle and Normal load

    "ay" : 0.0,                                                # lat acceleration
    "ra_Fy_required" : 0.0,                                    # Required Fy at RA according to ay demand
    "ra_Fy_inn" : 0.0, "ra_Fy_out" : 0.0,                      # RA inner and outer wheel lateral force Fy
    "ra_Fx_driven" : 0.0,                                      # RA driven wheel propulsion force
    "ra_Fx_out" : 0.0, "ra_Fx_inn" : 0.0,                      # RA outer and inner wheel lon force

    "fa_Fz_left" : 0.0, "fa_Fz_right" : 0.0,
    "ra_Fz_left" : 0.0, "ra_Fz_right" : 0.0,

    "ra_Mx_out": 0.0, "ra_My_out" : 0.0, "ra_Mz_out" : 0.0,
    "ra_Mx_inn": 0.0, "ra_My_inn" : 0.0, "ra_Mz_inn" : 0.0,

    "Fz_fa_brake" : 0.0, "Fz_ra_brake" : 0.0,
    "brake_ratio" : 0.0, "ratio_brake_dia_fa_to_ra" : 0.0,

    "driven_tire_wavelength_lim" : 0.0, "r_dyn" : 0.0,
    "static_driven_tire_wavelength_lim" : 0.0, "static_r_wheel" : 0.0,
    })

# =============================================================================
# C3 FIX: Entire self-test block moved inside `if __name__ == '__main__':` guard.
# Previously this ran at every import, polluting the EasyDict state and printing
# spurious output during the main simulation. Now it only runs when this file is
# executed directly (python Vehicle_Dynamics_V2.py).
# =============================================================================
if __name__ == '__main__':
    vd = VehicleDynamics(vehicle_config)

    vd.vertical_force_fatigue()
    vd.solve_cornering()
    vd.solve_propulsion()
    vd.static_wheel_parameters()

    # Calculate Outer Wheel Moments
    vehicle_config.ra_Mx_out = vd.solve_moment_x(vehicle_config.ra_Fz_out, vehicle_config.ra_Fy_out, vehicle_config.camber_angle)
    vehicle_config.ra_My_out = vd.solve_moment_y(vehicle_config.ra_Fx_out, vehicle_config.ra_Fz_out)
    vehicle_config.ra_Mz_out = vd.solve_moment_z(vehicle_config.ra_Fz_out, vehicle_config.alpha_deg)

    # Calculate Inner Wheel Moments
    vehicle_config.ra_Mx_inn = vd.solve_moment_x(vehicle_config.ra_Fz_inn, vehicle_config.ra_Fy_inn, vehicle_config.camber_angle)
    vehicle_config.ra_My_inn = vd.solve_moment_y(vehicle_config.ra_Fx_inn, vehicle_config.ra_Fz_inn)
    vehicle_config.ra_Mz_inn = vd.solve_moment_z(vehicle_config.ra_Fz_inn, vehicle_config.alpha_deg)

    print(f"cr = {vehicle_config.cr}, ra_Fz_pitch = {vehicle_config.ra_Fz_pitch}, ra_Fz_out = {vehicle_config.ra_Fz_out}")
    print(f"m_ra = {vehicle_config.m_ra}, del_h = {vehicle_config.del_h}")
    print(f"ra_Fy_inn = {vehicle_config.ra_Fy_inn}, ra_Fy_out = {vehicle_config.ra_Fy_out}, ra_Fy_required = {vehicle_config.ra_Fy_required}")
    print(f"ra_Fx_driven = {vehicle_config.ra_Fx_driven}, ra_Fx_inn = {vehicle_config.ra_Fx_inn}, ra_Fx_out = {vehicle_config.ra_Fx_out}")
    print(f"ra_Mx_out = {vehicle_config.ra_Mx_out}, ra_My_out = {vehicle_config.ra_My_out}, ra_Mz_out = {vehicle_config.ra_Mz_out}")
    print(f"ra_Mx_inn = {vehicle_config.ra_Mx_inn}, ra_My_inn = {vehicle_config.ra_My_inn}, ra_Mz_inn = {vehicle_config.ra_Mz_inn}")
    print(f"driven_tire_wavelength_lim = {vehicle_config.driven_tire_wavelength_lim * 100} cm")
