"""
main_simulation.py
==================
Master orchestrator for the Shell Eco-Marathon vehicle fatigue load simulation.

NOTE: pandas is NOT used (blocked by Windows AppControl on DLLs).
All CSV I/O is handled via stdlib csv + numpy.

Integrates:
  - canonical_drive_cycle_35min_1.csv  (measured speed vs time)
  - track_geometry.py                  (Silesia Ring club circuit geometry)
  - silesia_road_profile.py            (ISO 8608 road surface profile)
  - vertical_dynamics.py               (quarter-car suspension ODE)
  - Vehicle_Dynamics_V2.py             (steady-state 6-DOF loads & moments)

Output:
  - fatigue_loads_output.csv           (time-series forces & moments for Ansys)

Simulation strategy:
  1. Load CSV, resample to uniform 0.05 s time grid
  2. Compute distance from integrating speed
  3. Pre-solve quarter-car ODE over entire drive cycle (batch mode, fast)
  4. For each timestep, use track geometry to determine cornering state
  5. Call VehicleDynamics V2 solver for steady-state lateral/longitudinal loads
  6. Inject dynamic Fz from quarter-car into the steady-state result
  7. Compute hub moments and write to CSV

Authors: Generated by Antigravity AI for fatigue analysis workflows.
"""

import sys
import os
import warnings
import csv

# Force UTF-8 output on Windows consoles (fixes UnicodeEncodeError for Δ, ·, etc.)
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace', line_buffering=True)
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace', line_buffering=True)
import numpy as np
from scipy.interpolate import interp1d
from scipy.integrate import cumulative_trapezoid
from easydict import EasyDict as cfg

# ---------------------------------------------------------------------------
# Path setup — resolve sibling folders relative to DVFA root
# ---------------------------------------------------------------------------
# This script lives in:  <DVFA_ROOT>/03_Simulation_Runner/main_simulation.py
# All other folders are siblings of 03_Simulation_Runner inside DVFA_ROOT.
_SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
_DVFA_ROOT   = os.path.dirname(_SCRIPT_DIR)          # one level up = DVFA root

_MODELS_CORE = os.path.join(_DVFA_ROOT, '02_Physics_Models', 'Core_Vehicle_Dynamics')
_MODELS_SUSP = os.path.join(_DVFA_ROOT, '02_Physics_Models', 'Suspension_Quarter_Car')
_MODELS_ROAD = os.path.join(_DVFA_ROOT, '02_Physics_Models', 'Track_and_Road')

# Add all model folders to Python path
for _p in [_MODELS_CORE, _MODELS_SUSP, _MODELS_ROAD]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from track_geometry       import get_track_state, get_lap_length, compute_roll_gradient
from silesia_road_profile import SilesiaRoadProfile
from vertical_dynamics    import QuarterCarModel, ROCKSHOX_PARAMS
from motor_torque_model   import MotorTorqueModel, MOTOR_PARAMS

try:
    from Vehicle_Dynamics_V2 import VehicleDynamics
except ImportError:
    raise ImportError(
        "Could not import VehicleDynamics from Vehicle_Dynamics_V2.py.\n"
        f"Expected location: {_MODELS_CORE}"
    )

# ---------------------------------------------------------------------------
# Simulation I/O paths
# ---------------------------------------------------------------------------
CSV_PATH    = os.path.join(_DVFA_ROOT, '01_Input_Data', 'Drive_Cycle',
                           'canonical_drive_cycle_35min_1.csv')
OUTPUT_PATH = os.path.join(_DVFA_ROOT, '04_Output', 'CSV_Results',
                           'fatigue_loads_output.csv')
PLOT_DIR    = os.path.join(_DVFA_ROOT, '04_Output', 'Plots')

DT_UNIFORM  = 0.05          # uniform resampling interval [s]
LAP_LENGTH  = get_lap_length()  # metres (from track_geometry.py)
G           = 9.81

# ---------------------------------------------------------------------------
# Vehicle Configuration — matches Vehicle_Dynamics_V2.py defaults
# (modified each timestep with dynamic values from drive cycle + track)
# ---------------------------------------------------------------------------
def _make_vehicle_config() -> cfg:
    """Return a fresh vehicle_config EasyDict matching V2 defaults."""
    return cfg({
        # --- Variable (updated per timestep) ---
        "turn_radius":   -13.5,
        "velo_v":        35 / 3.6,
        "roll_angle":    np.radians(1.0),
        "bank_angle":    0.0,
        "inc_angle":     np.radians(3.0),
        "ax":            0.0,
        "lon_slip":      10.0,
        "motor_torque":  72.0,          # [N·m] placeholder — overwritten per timestep
        "camber_angle":  np.radians(0.0),

        # --- Fixed vehicle parameters (from V2) ---
        "s_r": 0.83, "s_f": 1.08,
        "m":   200.0,
        "cg_hei": 0.441,
        "fa_rp": 0.10161, "ra_rp": 0.0,
        "l_f": 0.7,  "l_r": 1.52 - 0.7,
        "m_spr": 160.0, "m_unspr": 40.0,
        "m_ra_unspr": 25.0, "m_fa_unspr": 15.0,
        "r_unloaded": 0.279,
        "k_ver": 220_000.0,
        "k_lat":  38_000.0,
        "roll_coeff": 0.0013,

        # --- Computed (zeroed initially) ---
        "wb": 0.0,
        "m_ra": 0.0,   "m_fa": 0.0,
        "m_ra_spr": 0.0, "m_fa_spr": 0.0,
        "del_h": 0.0,
        "ra_Fz_pitch": 0.0, "fa_Fz_pitch": 0.0,
        "delta_Fz_pitch": 0.0,
        "cf": 0.0,  "cr": 0.0,
        "fa_delta_Fz_roll": 0.0,  "ra_delta_Fz_roll": 0.0,
        "fa_delta_Fz_roll_lm": 0.0, "ra_delta_Fz_roll_lm": 0.0,
        "fa_Fz_out": 0.0,  "fa_Fz_inn": 0.0,  "fa_Fz_total": 0.0,
        "ra_Fz_out": 0.0,  "ra_Fz_inn": 0.0,  "ra_Fz_total": 0.0,
        "alpha_deg": 0.0,  "K": 0.0,
        "Fx_pure": 0.0,  "Fy_pure": 0.0,  "Fy_combined": 0.0,
        "ay": 0.0,
        "ra_Fy_required": 0.0,
        "ra_Fy_inn": 0.0, "ra_Fy_out": 0.0,
        "ra_Fx_driven": 0.0,
        "ra_Fx_out": 0.0, "ra_Fx_inn": 0.0,
        "fa_Fz_left": 0.0,  "fa_Fz_right": 0.0,
        "ra_Fz_left": 0.0,  "ra_Fz_right": 0.0,
        "ra_Mx_out": 0.0, "ra_My_out": 0.0, "ra_Mz_out": 0.0,
        "ra_Mx_inn": 0.0, "ra_My_inn": 0.0, "ra_Mz_inn": 0.0,
        "Fz_fa_brake": 0.0, "Fz_ra_brake": 0.0,
        "brake_ratio": 0.0, "ratio_brake_dia_fa_to_ra": 0.0,
        "driven_tire_wavelength_lim": 0.0, "r_dyn": 0.0,
        "static_driven_tire_wavelength_lim": 0.0, "static_r_wheel": 0.0,
    })


# ---------------------------------------------------------------------------
# Helper: derive lon_slip from longitudinal acceleration
# ---------------------------------------------------------------------------
def _ax_to_lon_slip(ax: float) -> float:
    """
    Estimate longitudinal slip [%] from vehicle acceleration [m/s²].
    Linear relationship, bounded at ±30%.
    Positive slip = acceleration side, Negative = braking side.
    """
    # Normalise by peak decel/accel that a 200 kg car can achieve (~0.3 g)
    slip = (ax / (0.3 * G)) * 30.0
    return float(np.clip(slip, -30.0, 30.0))


# ---------------------------------------------------------------------------
# Helper: compute roll angle from lateral acceleration
# ---------------------------------------------------------------------------
def _compute_roll_angle(ay: float, roll_gradient: float) -> float:
    """
    Estimate vehicle body roll angle [rad] from lateral acceleration [m/s²].
    roll_angle = ay × roll_gradient  [rad/m·s⁻²]
    Clamped to ±5° for physical realism.
    """
    roll = ay * roll_gradient
    return float(np.clip(roll, -np.radians(5.0), np.radians(5.0)))


# ---------------------------------------------------------------------------
# Helper: build static loads for stopped / very slow vehicle
# ---------------------------------------------------------------------------
def _static_loads(vd: VehicleDynamics) -> dict:
    """Return purely static corner loads when v ≈ 0."""
    p = vd.p
    Fz_static = p.m * G / 4.0    # equally distributed per corner
    return {
        'Fz_out': Fz_static, 'Fz_inn': Fz_static,
        'Fy_out': 0.0,       'Fy_inn': 0.0,
        'Fx_out': 0.0,       'Fx_inn': 0.0,
        'Mx_out': 0.0,       'Mx_inn': 0.0,
        'My_out': 0.0,       'My_inn': 0.0,
        'Mz_out': 0.0,       'Mz_inn': 0.0,
    }


# ---------------------------------------------------------------------------
# MAIN SIMULATION
# ---------------------------------------------------------------------------
def run_simulation(csv_path: str = CSV_PATH,
                   output_path: str = OUTPUT_PATH,
                   dt_uniform: float = DT_UNIFORM,
                   verbose: bool = True) -> dict:

    # ── 1. LOAD DRIVE CYCLE ────────────────────────────────────────────────
    if verbose:
        print("=" * 65)
        print("  Shell Eco-Marathon — Full Vehicle Fatigue Simulation")
        print("  Silesia Ring Club Circuit — 35-minute Drive Cycle")
        print("=" * 65)
        print(f"\n[1/7] Loading drive cycle: {csv_path}")

    # Read CSV with stdlib — no pandas needed
    t_list, v_list = [], []
    with open(csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        seen_t = set()
        for row in reader:
            try:
                t_val = float(row['elapsed_sec'])
                v_val = float(row['Speed_kmh'])
            except (ValueError, KeyError):
                continue
            if t_val in seen_t:
                continue
            seen_t.add(t_val)
            t_list.append(t_val)
            v_list.append(v_val)

    # Sort by time
    order  = np.argsort(t_list)
    t_raw  = np.array(t_list, dtype=float)[order]
    v_kmh  = np.array(v_list, dtype=float)[order]
    v_ms   = v_kmh / 3.6   # convert to m/s

    t_end = t_raw[-1]
    if verbose:
        print(f"    Raw data: {len(t_raw)} points, duration = {t_end:.1f} s  "
              f"({t_end/60:.1f} min)")
        print(f"    Speed range: {v_kmh.min():.1f} – {v_kmh.max():.1f} km/h")

    # ── 2. RESAMPLE TO UNIFORM TIME GRID ──────────────────────────────────
    if verbose:
        print(f"\n[2/7] Resampling to uniform Δt = {dt_uniform*1000:.0f} ms grid")

    t_uni  = np.arange(0.0, t_end, dt_uniform)
    v_interp = interp1d(t_raw, v_ms, kind='linear',
                        bounds_error=False, fill_value=(v_ms[0], v_ms[-1]))
    v_uni  = np.clip(v_interp(t_uni), 0.0, None)   # [m/s], non-negative

    N = len(t_uni)
    if verbose:
        print(f"    Uniform grid: {N:,} timesteps")

    # ── 3. COMPUTE DERIVED SIGNALS ────────────────────────────────────────
    if verbose:
        print(f"\n[3/7] Computing ax, distance, track position")

    # Longitudinal acceleration (central difference, smoothed)
    ax_uni = np.gradient(v_uni, t_uni)
    # Light smoothing (50-sample rolling mean ≈ 2.5 s)
    kern   = np.ones(25) / 25.0
    ax_uni = np.convolve(ax_uni, kern, mode='same')

    # Cumulative distance [m]
    dist_m = np.zeros(N)
    dist_m[1:] = cumulative_trapezoid(v_uni, t_uni)

    # Track position (modulo lap length)
    d_track = dist_m % LAP_LENGTH

    total_dist_km = dist_m[-1] / 1000.0
    n_laps = dist_m[-1] / LAP_LENGTH
    if verbose:
        print(f"    Total distance : {total_dist_km:.2f} km")
        print(f"    Laps completed : {n_laps:.1f}  (lap = {LAP_LENGTH:.0f} m)")

    # ── 4. GENERATE ROAD PROFILE ──────────────────────────────────────────
    if verbose:
        print(f"\n[4/7] Generating Silesia Ring road profile (ISO 8608)")

    road_profile = SilesiaRoadProfile(lap_length_m=LAP_LENGTH, dx=0.02, random_seed=42)
    z_road_uni = np.array([road_profile.get_displacement(d) for d in d_track])

    if verbose:
        print(f"    RMS road roughness: {np.sqrt(np.mean(z_road_uni**2))*1000:.2f} mm")

    # ── 5. SOLVE QUARTER-CAR ODE (BATCH) ──────────────────────────────────
    if verbose:
        print(f"\n[5/7] Solving quarter-car ODE (RockShox Super Deluxe Select+)")

    qcar = QuarterCarModel(ROCKSHOX_PARAMS)
    if verbose:
        print(f"    {qcar.summary()}")

    Fz_dyn_outer, z_sprung, z_unsprung = qcar.solve_batch(t_uni, z_road_uni)

    # C1 FIX: The solve_batch above now starts from equilibrium at z_road[0].
    # To eliminate the initial transient spike (reported 8071 N artifact), we
    # discard the first WARMUP_SECS seconds of ODE output and fill them with
    # the first valid (post-transient) value.
    WARMUP_SECS = 2.0
    warmup_idx  = int(WARMUP_SECS / dt_uniform)
    warmup_idx  = min(warmup_idx, N - 1)
    fill_val    = Fz_dyn_outer[warmup_idx]
    Fz_dyn_outer[:warmup_idx] = fill_val

    # H1 FIX: Inner wheel Fz_dyn is now CORRELATED (same-sign) with outer.
    # Both rear wheels traverse the same road profile — longitudinal bumps
    # affect both wheels in the same direction simultaneously. The inner/outer
    # LOAD SPLIT is already handled by V2's pitch+roll model via dyn_ratio.
    # Previous model (anti-correlated 0.6× mirror) was physically wrong.
    # New model: inner sees the same dynamic fluctuation as outer; the
    # slightly lower static preload is captured by scaling from V2 output.
    Fz_static_corner = (qcar.ms + qcar.mu) * G
    Fz_dyn_inner = Fz_dyn_outer.copy()   # same road, same direction of bump
    Fz_dyn_inner = np.maximum(Fz_dyn_inner, 0.0)

    if verbose:
        print(f"    Peak dynamic Fz (outer): {Fz_dyn_outer.max():.1f} N  "
              f"(+{(Fz_dyn_outer.max()/Fz_static_corner - 1)*100:.0f}% above static)")
        print(f"    [C1] Warm-up: first {WARMUP_SECS:.0f}s filled with {fill_val:.1f} N (transient discarded)")


    # ── 6. COMPUTE DYNAMIC MOTOR TORQUE ──────────────────────────────────
    if verbose:
        print(f"\n[6a/7] Pre-computing physics-based motor torque (resistance model)")

    # Initialize here so we can access vehicle mass
    vehicle_config = _make_vehicle_config()

    mtm = MotorTorqueModel(MOTOR_PARAMS)
    # Update mass to match the full simulation vehicle mass (not the 180 kg MATLAB default)
    mtm.m = vehicle_config.m   # 200 kg
    if verbose:
        print(f"    {mtm.summary()}")

    torque_uni = mtm.compute_batch(v_uni, ax_uni)   # shape (N,)  [N·m]

    if verbose:
        moving_mask = v_uni > 0.1
        print(f"    Torque range (moving): "
              f"{torque_uni[moving_mask].min():.1f} – "
              f"{torque_uni[moving_mask].max():.1f} N·m")
        print(f"    Mean torque (moving):  {torque_uni[moving_mask].mean():.1f} N·m  "
              f"(was: 72.0 N·m constant)")
        print(f"    Coasting timesteps:    "
              f"{np.sum(torque_uni == 0):,} / {N:,}  "
              f"({100*np.sum(torque_uni == 0)/N:.1f}%)")

    # ── 7. SETUP VEHICLE DYNAMICS ─────────────────────────────────────────
    if verbose:
        print(f"\n[6/7] Running Vehicle_Dynamics_V2 over {N:,} timesteps ...")

    vd = VehicleDynamics(vehicle_config)

    # Pre-compute roll gradient from suspension params
    roll_grad_params = {
        'ks_suspension': ROCKSHOX_PARAMS['ks'],
        's_f': vehicle_config.s_f,
        's_r': vehicle_config.s_r,
        'm_spr': vehicle_config.m_spr,
        'del_h': vd.p.del_h,   # computed by __init__
    }
    roll_gradient = compute_roll_gradient(roll_grad_params)
    if verbose:
        print(f"    Roll gradient: {np.degrees(roll_gradient):.3f} °/(m/s²)  "
              f"[{roll_gradient*G:.3f} °/g]")

    MIN_SPEED_MS    = 0.5     # [m/s] below this: static loads only
    MIN_TURN_RAD    = 5.0     # [m] below this radius: skip cornering (numerical guard)
    STRAIGHT_RAD    = 9000.0  # [m] treat as straight above this threshold

    # ── 7. TIMESTEP LOOP ──────────────────────────────────────────────────
    # Pre-allocate output columns
    results = {
        'time_s':           np.zeros(N),
        'distance_m':       np.zeros(N),
        'speed_kmh':        np.zeros(N),
        'ax_ms2':           np.zeros(N),
        'turn_radius_m':    np.zeros(N),
        'inc_angle_deg':    np.zeros(N),
        'bank_angle_deg':   np.zeros(N),
        'segment':          [''] * N,
        # Outer RA wheel loads
        'Fz_outer_N':       np.zeros(N),
        'Fy_outer_N':       np.zeros(N),
        'Fx_outer_N':       np.zeros(N),
        'Mx_outer_Nm':      np.zeros(N),
        'My_outer_Nm':      np.zeros(N),
        'Mz_outer_Nm':      np.zeros(N),
        # Inner RA wheel loads
        'Fz_inner_N':       np.zeros(N),
        'Fy_inner_N':       np.zeros(N),
        'Fx_inner_N':       np.zeros(N),
        'Mx_inner_Nm':      np.zeros(N),
        'My_inner_Nm':      np.zeros(N),
        'Mz_inner_Nm':      np.zeros(N),
        # Vertical dynamics
        'Fz_dyn_outer_N':   np.zeros(N),
        'Fz_dyn_inner_N':   np.zeros(N),
        'z_road_m':         np.zeros(N),
        'z_sprung_m':       np.zeros(N),
        # Motor torque (dynamic, from resistance model)
        'motor_torque_Nm':  np.zeros(N),
    }

    # Progress reporting
    n_report  = max(1, N // 20)
    n_static  = 0
    n_corner  = 0
    n_errors  = 0

    for i in range(N):
        t  = t_uni[i]
        v  = v_uni[i]
        ax = ax_uni[i]
        d  = dist_m[i]

        # Basic signals
        results['time_s'][i]     = t
        results['distance_m'][i] = d
        results['speed_kmh'][i]  = v * 3.6
        results['ax_ms2'][i]     = ax
        results['z_road_m'][i]       = z_road_uni[i]
        results['z_sprung_m'][i]     = z_sprung[i]
        results['Fz_dyn_outer_N'][i] = Fz_dyn_outer[i]
        results['Fz_dyn_inner_N'][i] = Fz_dyn_inner[i]
        results['motor_torque_Nm'][i] = torque_uni[i]

        # Track state at current position
        ts = get_track_state(d)
        turn_r = ts['turn_radius']
        inc    = ts['inc_angle']
        bank   = ts['bank_angle']
        results['turn_radius_m'][i]  = turn_r
        results['inc_angle_deg'][i]  = np.degrees(inc)
        results['bank_angle_deg'][i] = np.degrees(bank)
        results['segment'][i]        = ts['segment_name']

        try:
            if v < MIN_SPEED_MS:
                # --- STATIC CASE: vehicle stopped or near-stopped ---
                n_static += 1
                sl = _static_loads(vd)
                # Dynamic Fz injection (still valid even at standstill)
                sl['Fz_out'] = Fz_dyn_outer[i]
                sl['Fz_inn'] = Fz_dyn_inner[i]

            else:
                # --- DYNAMIC CASE ---
                n_corner += 1

                # Lateral acceleration for this corner
                is_straight = abs(turn_r) >= STRAIGHT_RAD
                if is_straight or abs(turn_r) < MIN_TURN_RAD:
                    ay_est = 0.0
                    eff_turn_r = 9999.0
                else:
                    ay_est     = (v ** 2) / abs(turn_r)
                    eff_turn_r = turn_r

                # Dynamic roll angle
                roll = _compute_roll_angle(ay_est, roll_gradient)
                if abs(roll) < 1e-5:
                    roll = 0.0   # stays zero on straights — early exit in V2

                # Longitudinal slip estimate
                lon_slip = _ax_to_lon_slip(ax)

                # Update vehicle config for this timestep
                p = vd.p
                p.velo_v      = float(v)
                p.ax          = float(ax)
                p.turn_radius = float(eff_turn_r)
                p.inc_angle   = float(inc)
                p.bank_angle  = float(bank)
                p.roll_angle  = float(roll)
                p.lon_slip    = float(lon_slip)
                p.motor_torque = float(torque_uni[i])   # dynamic torque [N·m]

                # --- Solve V2 ---
                vd.vertical_force_fatigue()   # pitch + roll → Fz per wheel

                if not is_straight and abs(eff_turn_r) >= MIN_TURN_RAD:
                    vd.solve_cornering()       # Fy via PAC89 kremple
                else:
                    # On straights: zero lateral forces
                    p.ra_Fy_out = 0.0
                    p.ra_Fy_inn = 0.0
                    p.alpha_deg = 0.0

                vd.solve_propulsion()          # Fx (inner wheel driven)

                # M1 FIX: Rolling resistance Fx on outer wheel.
                # Open-diff gives ra_Fx_out=0 (no drive torque), but rolling
                # resistance still acts as a retarding force on both wheels.
                # Fx_rr = -roll_coeff * Fz  (negative = opposing motion)
                Fx_rr_out = -vd.p.roll_coeff * p.ra_Fz_out

                # --- INJECT dynamic Fz from quarter-car ---
                # Scale static Fz values by dynamic/static ratio
                # preserving the inner/outer load split
                Fz_static_total = p.ra_Fz_out + p.ra_Fz_inn
                if Fz_static_total > 1.0:
                    dyn_ratio_out = Fz_dyn_outer[i] / (Fz_static_total / 2.0)
                    dyn_ratio_inn = Fz_dyn_inner[i] / (Fz_static_total / 2.0)
                else:
                    dyn_ratio_out = 1.0
                    dyn_ratio_inn = 1.0

                Fz_out_final = p.ra_Fz_out * dyn_ratio_out
                Fz_inn_final = p.ra_Fz_inn * dyn_ratio_inn

                # Compute hub moments with dynamic Fz
                Mx_out = vd.solve_moment_x(Fz_out_final, p.ra_Fy_out, p.camber_angle)
                My_out = vd.solve_moment_y(p.ra_Fx_out,  Fz_out_final)
                Mz_out = vd.solve_moment_z(Fz_out_final, p.alpha_deg)

                Mx_inn = vd.solve_moment_x(Fz_inn_final, p.ra_Fy_inn, p.camber_angle)
                My_inn = vd.solve_moment_y(p.ra_Fx_inn,  Fz_inn_final)
                Mz_inn = vd.solve_moment_z(Fz_inn_final, p.alpha_deg)

                sl = {
                    'Fz_out': Fz_out_final, 'Fz_inn': Fz_inn_final,
                    'Fy_out': p.ra_Fy_out,  'Fy_inn': p.ra_Fy_inn,
                    'Fx_out': Fx_rr_out,    'Fx_inn': p.ra_Fx_inn,
                    'Mx_out': Mx_out,        'Mx_inn': Mx_inn,
                    'My_out': My_out,        'My_inn': My_inn,
                    'Mz_out': Mz_out,        'Mz_inn': Mz_inn,
                }

            # Store results
            results['Fz_outer_N'][i]  = sl['Fz_out']
            results['Fy_outer_N'][i]  = sl['Fy_out']
            results['Fx_outer_N'][i]  = sl['Fx_out']
            results['Mx_outer_Nm'][i] = sl['Mx_out']
            results['My_outer_Nm'][i] = sl['My_out']
            results['Mz_outer_Nm'][i] = sl['Mz_out']

            results['Fz_inner_N'][i]  = sl['Fz_inn']
            results['Fy_inner_N'][i]  = sl['Fy_inn']
            results['Fx_inner_N'][i]  = sl['Fx_inn']
            results['Mx_inner_Nm'][i] = sl['Mx_inn']
            results['My_inner_Nm'][i] = sl['My_inn']
            results['Mz_inner_Nm'][i] = sl['Mz_inn']

        except Exception as e:
            n_errors += 1
            warnings.warn(f"Timestep {i} (t={t:.2f}s) error: {e}")
            # Fill with previous value on error
            if i > 0:
                for col in ['Fz_outer_N','Fy_outer_N','Fx_outer_N',
                            'Mx_outer_Nm','My_outer_Nm','Mz_outer_Nm',
                            'Fz_inner_N','Fy_inner_N','Fx_inner_N',
                            'Mx_inner_Nm','My_inner_Nm','Mz_inner_Nm']:
                    results[col][i] = results[col][i-1]

        # Progress report
        if verbose and i % n_report == 0:
            pct = 100 * i / N
            print(f"    {pct:5.1f}%  t={t:7.1f}s  v={v*3.6:5.1f}km/h  "
                  f"seg={ts['segment_name']:<28}  "
                  f"Fz_out={results['Fz_outer_N'][i]:6.0f}N")

    # ── 8. WRITE OUTPUT CSV ───────────────────────────────────────────────
    if verbose:
        print(f"\n[7/7] Writing results to: {output_path}")

    col_order = [
        'time_s','distance_m','speed_kmh','ax_ms2','turn_radius_m',
        'inc_angle_deg','bank_angle_deg','segment',
        'motor_torque_Nm',
        'Fz_outer_N','Fy_outer_N','Fx_outer_N','Mx_outer_Nm','My_outer_Nm','Mz_outer_Nm',
        'Fz_inner_N','Fy_inner_N','Fx_inner_N','Mx_inner_Nm','My_inner_Nm','Mz_inner_Nm',
        'Fz_dyn_outer_N','Fz_dyn_inner_N','z_road_m','z_sprung_m',
    ]
    # C2 FIX: Sweep all output float arrays for NaN / Inf before writing.
    # NaN values were caused by (a) V2 module-level self-test state leaking
    # into t=0 (now fixed by C3), and (b) solve_moment_z divide/0 on Mz
    # when Fz=0 at standstill. Replace with 0.0 (static case = no aligning torque).
    float_cols = [c for c in col_order if c != 'segment']
    for col in float_cols:
        if col in results and isinstance(results[col], np.ndarray):
            nan_count = int(np.sum(~np.isfinite(results[col])))
            if nan_count > 0:
                results[col] = np.nan_to_num(results[col], nan=0.0, posinf=0.0, neginf=0.0)
                if verbose:
                    print(f"    [C2] NaN/Inf fixed in '{col}': {nan_count} values replaced with 0")

    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(col_order)
        for i in range(N):
            row = []
            for c in col_order:
                v_cell = results[c][i]
                if isinstance(v_cell, float):
                    row.append(round(v_cell, 4))
                else:
                    row.append(v_cell)
            writer.writerow(row)
    file_size_mb = os.path.getsize(output_path) / 1e6

    if verbose:
        print(f"\n{'='*65}")
        print(f"  SIMULATION COMPLETE")
        print(f"{'='*65}")
        print(f"  Output file    : {output_path}")
        print(f"  File size      : {file_size_mb:.1f} MB")
        print(f"  Total rows     : {N:,}")
        print(f"  Timestep Δt    : {dt_uniform*1000:.0f} ms")
        print(f"  Static pts     : {n_static:,}  ({100*n_static/N:.1f}%)")
        print(f"  Dynamic pts    : {n_corner:,}  ({100*n_corner/N:.1f}%)")
        print(f"  Solver errors  : {n_errors}")
        print(f"\n  ── Peak Loads Summary (RA outer wheel) ──")
        print(f"  Fz_outer  max  : {results['Fz_outer_N'].max():.1f} N")
        print(f"  Fz_outer  min  : {results['Fz_outer_N'].min():.1f} N")
        print(f"  Fy_outer  max  : {results['Fy_outer_N'].max():.1f} N")
        print(f"  Fx_outer  max  : {results['Fx_outer_N'].max():.1f} N")
        print(f"  Mx_outer  max  : {results['Mx_outer_Nm'].max():.1f} N·m")
        print(f"  My_outer  max  : {results['My_outer_Nm'].max():.1f} N·m")
        print(f"  Mz_outer  max  : {results['Mz_outer_Nm'].max():.1f} N·m")
        print(f"  Fz_dyn_outer max: {results['Fz_dyn_outer_N'].max():.1f} N  "
              f"(vs static {(qcar.ms+qcar.mu)*G:.1f} N)")

    return results


# ---------------------------------------------------------------------------
# Optional: plot summary
# ---------------------------------------------------------------------------
def plot_results(results: dict, save_dir: str = PLOT_DIR):
    try:
        import matplotlib.pyplot as plt
        import matplotlib.gridspec as gridspec

        fig = plt.figure(figsize=(16, 10))
        gs  = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.35)

        t = results['time_s']

        def _ax_plot(ax, y, title, unit, color='steelblue'):
            ax.plot(t, y, lw=0.4, color=color, alpha=0.85)
            ax.set_title(title, fontsize=9)
            ax.set_ylabel(unit, fontsize=8)
            ax.set_xlabel('Time [s]', fontsize=8)
            ax.tick_params(labelsize=7)
            ax.grid(True, alpha=0.3)

        _ax_plot(fig.add_subplot(gs[0, 0]), results['speed_kmh'],   'Speed',          'km/h', 'navy')
        _ax_plot(fig.add_subplot(gs[0, 1]), results['ax_ms2'],      'Long. Accel.',   'm/s²', 'darkorange')
        _ax_plot(fig.add_subplot(gs[0, 2]), np.clip(results['turn_radius_m'], -200, 200),
                                                                     'Turn Radius',    'm',    'purple')

        _ax_plot(fig.add_subplot(gs[1, 0]), results['Fz_outer_N'],  'Fz Outer',       'N',    'crimson')
        _ax_plot(fig.add_subplot(gs[1, 1]), results['Fy_outer_N'],  'Fy Outer',       'N',    'darkcyan')
        _ax_plot(fig.add_subplot(gs[1, 2]), results['Fx_outer_N'],  'Fx Outer',       'N',    'darkgreen')

        _ax_plot(fig.add_subplot(gs[2, 0]), results['Mx_outer_Nm'], 'Mx Outer',       'N·m',  'saddlebrown')
        _ax_plot(fig.add_subplot(gs[2, 1]), results['My_outer_Nm'], 'My Outer',       'N·m',  'darkolivegreen')
        _ax_plot(fig.add_subplot(gs[2, 2]), results['Fz_dyn_outer_N'], 'Fz Dynamic',  'N',    'darkviolet')

        fig.suptitle('Shell Eco-Marathon — Silesia Ring — 35-min Fatigue Load History',
                     fontsize=12, fontweight='bold')

        out_png = os.path.join(save_dir, 'fatigue_loads_summary.png')
        plt.savefig(out_png, dpi=150, bbox_inches='tight')
        print(f"\nSummary plot saved: {out_png}")
        plt.show()
    except ImportError:
        print("(matplotlib not available for plotting)")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    results = run_simulation(verbose=True)
    plot_results(results, save_dir=PLOT_DIR)
    print("\nDone. Open 04_Output/CSV_Results/fatigue_loads_output.csv for Ansys import.")
