"""Stage 7 delivery — turn the digest into deliverable artifacts and (optionally) send.

Agent-agnostic by design: every agent has a different send channel (OpenClaw Gmail/
Telegram, a Gmail MCP tool, plain SMTP). So this module always WRITES the artifacts
(HTML email + plaintext + a short one-liner) and additionally SENDS them only if SMTP
creds are present in secrets.yml. Otherwise the calling agent sends the artifact with
its own tool. Same outputs everywhere.
"""
from __future__ import annotations

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date
from pathlib import Path

from .config import output_dir
from .db import DB


def _rank(db: DB, min_score: int, top_n: int) -> list[dict]:
    scored = [j for j in db.all()
              if j.get("score") is not None and j["state"] not in ("rejected",)]
    scored = [j for j in scored if (j.get("score") or 0) >= min_score]
    return sorted(scored, key=lambda j: j.get("score") or 0, reverse=True)[:top_n]


def _html(jobs: list[dict]) -> str:
    today = date.today().isoformat()
    rows = []
    for i, j in enumerate(jobs, 1):
        sj = j.get("score_json") or {}
        tags = " · ".join(filter(None, [
            sj.get("sector"), "PhD" if sj.get("is_phd") else "",
            f"DE:{sj['german_required']}" if sj.get("german_required") else "",
            f"tier {sj.get('tier')}" if sj.get("tier") else ""]))
        reasons = "".join(f"<li>{r}</li>" for r in (sj.get("reasons") or [])[:4])
        rows.append(f"""
        <div style="margin:0 0 18px;padding:14px 16px;border:1px solid #e3e3e3;border-radius:10px">
          <div style="font-size:16px;font-weight:600">{i}. {j['title']}
            <span style="color:#1a7f37">({j.get('score','?')}/100)</span></div>
          <div style="color:#444">{j['company']} — {j.get('location') or 'location n/a'}</div>
          <div style="color:#888;font-size:12px;margin:2px 0 6px">{tags}</div>
          <ul style="margin:6px 0 8px;padding-left:18px;color:#333">{reasons}</ul>
          <a href="{j.get('url','#')}" style="color:#0969da">Open posting →</a>
          <span style="color:#aaa;font-size:12px"> · id {j['id']} · {j['state']}</span>
        </div>""")
    body = "".join(rows) or "<p>No new matches above threshold today.</p>"
    return f"""<!doctype html><html><body style="font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:680px;margin:auto;color:#111">
      <h2>Fuel-cell job digest — {today}</h2>
      <p style="color:#555">{len(jobs)} top matches. Reply <code>approve &lt;id&gt;</code> or <code>reject &lt;id&gt;</code>.</p>
      {body}
      <hr><p style="color:#999;font-size:12px">Generated by the job-automation skill.</p>
    </body></html>"""


def build_artifacts(db: DB, min_score: int = 50, top_n: int = 15) -> dict[str, str]:
    jobs = _rank(db, min_score, top_n)
    out = output_dir()
    html = _html(jobs)
    short = (f"Job digest {date.today().isoformat()}: {len(jobs)} matches. "
             + "; ".join(f"{j['company']} {j['title']} ({j['score']})" for j in jobs[:3]))
    plain_lines = [f"{i}. {j['title']} — {j['company']} ({j.get('score','?')}) {j.get('url','')}"
                   for i, j in enumerate(jobs, 1)]
    plain = "Fuel-cell job digest\n\n" + "\n".join(plain_lines)
    paths = {
        "html": str(out / "digest_email.html"),
        "txt": str(out / "digest_plain.txt"),
        "short": str(out / "digest_short.txt"),
    }
    Path(paths["html"]).write_text(html, encoding="utf-8")
    Path(paths["txt"]).write_text(plain, encoding="utf-8")
    Path(paths["short"]).write_text(short, encoding="utf-8")
    return paths


def send_smtp(secrets: dict, to_addr: str, subject: str, html_path: str) -> str:
    s = secrets.get("smtp", {})
    host, port = s.get("host"), s.get("port", 587)
    user, pw = s.get("user"), s.get("password")
    if not (host and user and pw):
        return "skipped: no smtp creds in secrets.yml (agent should send the artifact itself)"
    msg = MIMEMultipart("alternative")
    msg["Subject"], msg["From"], msg["To"] = subject, user, to_addr
    msg.attach(MIMEText(Path(html_path).read_text(encoding="utf-8"), "html"))
    with smtplib.SMTP(host, port) as srv:
        srv.starttls()
        srv.login(user, pw)
        srv.sendmail(user, [to_addr], msg.as_string())
    return f"sent to {to_addr} via {host}"
